/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppContasRouteImport } from './routes/_app/contas'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppTransacoesIndexRouteImport } from './routes/_app/transacoes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppTransacoesIndexRoute = AppTransacoesIndexRouteImport.update({
  id: '/transacoes/',
  path: '/transacoes/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/categorias': typeof AppCategoriasRoute
  '/contas': typeof AppContasRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/transacoes/': typeof AppTransacoesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/categorias': typeof AppCategoriasRoute
  '/contas': typeof AppContasRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/transacoes': typeof AppTransacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/contas': typeof AppContasRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/transacoes/': typeof AppTransacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/registrar'
    | '/categorias'
    | '/contas'
    | '/api/auth/$'
    | '/transacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/registrar'
    | '/categorias'
    | '/contas'
    | '/'
    | '/api/auth/$'
    | '/transacoes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/registrar'
    | '/_app/categorias'
    | '/_app/contas'
    | '/_app/'
    | '/api/auth/$'
    | '/_app/transacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistrarRoute: typeof RegistrarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas': {
      id: '/_app/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transacoes/': {
      id: '/_app/transacoes/'
      path: '/transacoes'
      fullPath: '/transacoes/'
      preLoaderRoute: typeof AppTransacoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppContasRoute: typeof AppContasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTransacoesIndexRoute: typeof AppTransacoesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppContasRoute: AppContasRoute,
  AppIndexRoute: AppIndexRoute,
  AppTransacoesIndexRoute: AppTransacoesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistrarRoute: RegistrarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
