/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRecorrentesRouteImport } from './routes/_app/recorrentes'
import { Route as AppOrcamentosRouteImport } from './routes/_app/orcamentos'
import { Route as AppContasRouteImport } from './routes/_app/contas'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppTransacoesIndexRouteImport } from './routes/_app/transacoes/index'
import { Route as AppObjetivosIndexRouteImport } from './routes/_app/objetivos/index'
import { Route as AppCartoesIndexRouteImport } from './routes/_app/cartoes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTransacoesImportarRouteImport } from './routes/_app/transacoes/importar'
import { Route as AppObjetivosGoalIdRouteImport } from './routes/_app/objetivos/$goalId'
import { Route as AppCartoesCardIdRouteImport } from './routes/_app/cartoes/$cardId'

const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecorrentesRoute = AppRecorrentesRouteImport.update({
  id: '/recorrentes',
  path: '/recorrentes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppTransacoesIndexRoute = AppTransacoesIndexRouteImport.update({
  id: '/transacoes/',
  path: '/transacoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppObjetivosIndexRoute = AppObjetivosIndexRouteImport.update({
  id: '/objetivos/',
  path: '/objetivos/',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesIndexRoute = AppCartoesIndexRouteImport.update({
  id: '/cartoes/',
  path: '/cartoes/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesImportarRoute = AppTransacoesImportarRouteImport.update({
  id: '/transacoes/importar',
  path: '/transacoes/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppObjetivosGoalIdRoute = AppObjetivosGoalIdRouteImport.update({
  id: '/objetivos/$goalId',
  path: '/objetivos/$goalId',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesCardIdRoute = AppCartoesCardIdRouteImport.update({
  id: '/cartoes/$cardId',
  path: '/cartoes/$cardId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/categorias': typeof AppCategoriasRoute
  '/contas': typeof AppContasRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/recorrentes': typeof AppRecorrentesRoute
  '/cartoes/$cardId': typeof AppCartoesCardIdRoute
  '/objetivos/$goalId': typeof AppObjetivosGoalIdRoute
  '/transacoes/importar': typeof AppTransacoesImportarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cartoes/': typeof AppCartoesIndexRoute
  '/objetivos/': typeof AppObjetivosIndexRoute
  '/transacoes/': typeof AppTransacoesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/categorias': typeof AppCategoriasRoute
  '/contas': typeof AppContasRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/recorrentes': typeof AppRecorrentesRoute
  '/': typeof AppIndexRoute
  '/cartoes/$cardId': typeof AppCartoesCardIdRoute
  '/objetivos/$goalId': typeof AppObjetivosGoalIdRoute
  '/transacoes/importar': typeof AppTransacoesImportarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cartoes': typeof AppCartoesIndexRoute
  '/objetivos': typeof AppObjetivosIndexRoute
  '/transacoes': typeof AppTransacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/registrar': typeof RegistrarRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/contas': typeof AppContasRoute
  '/_app/orcamentos': typeof AppOrcamentosRoute
  '/_app/recorrentes': typeof AppRecorrentesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/cartoes/$cardId': typeof AppCartoesCardIdRoute
  '/_app/objetivos/$goalId': typeof AppObjetivosGoalIdRoute
  '/_app/transacoes/importar': typeof AppTransacoesImportarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/cartoes/': typeof AppCartoesIndexRoute
  '/_app/objetivos/': typeof AppObjetivosIndexRoute
  '/_app/transacoes/': typeof AppTransacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/registrar'
    | '/categorias'
    | '/contas'
    | '/orcamentos'
    | '/recorrentes'
    | '/cartoes/$cardId'
    | '/objetivos/$goalId'
    | '/transacoes/importar'
    | '/api/auth/$'
    | '/cartoes/'
    | '/objetivos/'
    | '/transacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/registrar'
    | '/categorias'
    | '/contas'
    | '/orcamentos'
    | '/recorrentes'
    | '/'
    | '/cartoes/$cardId'
    | '/objetivos/$goalId'
    | '/transacoes/importar'
    | '/api/auth/$'
    | '/cartoes'
    | '/objetivos'
    | '/transacoes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/registrar'
    | '/_app/categorias'
    | '/_app/contas'
    | '/_app/orcamentos'
    | '/_app/recorrentes'
    | '/_app/'
    | '/_app/cartoes/$cardId'
    | '/_app/objetivos/$goalId'
    | '/_app/transacoes/importar'
    | '/api/auth/$'
    | '/_app/cartoes/'
    | '/_app/objetivos/'
    | '/_app/transacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistrarRoute: typeof RegistrarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recorrentes': {
      id: '/_app/recorrentes'
      path: '/recorrentes'
      fullPath: '/recorrentes'
      preLoaderRoute: typeof AppRecorrentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos': {
      id: '/_app/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas': {
      id: '/_app/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transacoes/': {
      id: '/_app/transacoes/'
      path: '/transacoes'
      fullPath: '/transacoes/'
      preLoaderRoute: typeof AppTransacoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/objetivos/': {
      id: '/_app/objetivos/'
      path: '/objetivos'
      fullPath: '/objetivos/'
      preLoaderRoute: typeof AppObjetivosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/': {
      id: '/_app/cartoes/'
      path: '/cartoes'
      fullPath: '/cartoes/'
      preLoaderRoute: typeof AppCartoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transacoes/importar': {
      id: '/_app/transacoes/importar'
      path: '/transacoes/importar'
      fullPath: '/transacoes/importar'
      preLoaderRoute: typeof AppTransacoesImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/objetivos/$goalId': {
      id: '/_app/objetivos/$goalId'
      path: '/objetivos/$goalId'
      fullPath: '/objetivos/$goalId'
      preLoaderRoute: typeof AppObjetivosGoalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/$cardId': {
      id: '/_app/cartoes/$cardId'
      path: '/cartoes/$cardId'
      fullPath: '/cartoes/$cardId'
      preLoaderRoute: typeof AppCartoesCardIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppContasRoute: typeof AppContasRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppRecorrentesRoute: typeof AppRecorrentesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCartoesCardIdRoute: typeof AppCartoesCardIdRoute
  AppObjetivosGoalIdRoute: typeof AppObjetivosGoalIdRoute
  AppTransacoesImportarRoute: typeof AppTransacoesImportarRoute
  AppCartoesIndexRoute: typeof AppCartoesIndexRoute
  AppObjetivosIndexRoute: typeof AppObjetivosIndexRoute
  AppTransacoesIndexRoute: typeof AppTransacoesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppContasRoute: AppContasRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppRecorrentesRoute: AppRecorrentesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCartoesCardIdRoute: AppCartoesCardIdRoute,
  AppObjetivosGoalIdRoute: AppObjetivosGoalIdRoute,
  AppTransacoesImportarRoute: AppTransacoesImportarRoute,
  AppCartoesIndexRoute: AppCartoesIndexRoute,
  AppObjetivosIndexRoute: AppObjetivosIndexRoute,
  AppTransacoesIndexRoute: AppTransacoesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistrarRoute: RegistrarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
